[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.9.0",
    "click>=8.2.1",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "structlog>=25.4.0",
]
