# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/whoismcp/mcp_server.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'whoismcp',
        'whoismcp.config',
        'whoismcp.models',
        'whoismcp.models.domain_models',
        'whoismcp.models.mcp_models',
        'whoismcp.services',
        'whoismcp.services.cache_service',
        'whoismcp.services.rdap_service',
        'whoismcp.services.whois_service',
        'whoismcp.utils',
        'whoismcp.utils.parsers',
        'whoismcp.utils.rate_limiter',
        'whoismcp.utils.validators',
        'anyio._backends._asyncio',
        'httpx',
        'httpcore',
        'httpcore._async',
        'httpcore._sync',
        'certifi',
        'structlog',
        'pydantic',
        'pydantic_core',
        'click',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'pytest_asyncio',
        'pytest_cov',
        'black',
        'ruff',
        'mypy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='whoismcp-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
